# Generated by Django 5.1.3 on 2025-02-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
